dependencies {
    // Librería para EncryptedSharedPreferences
    implementation "androidx.security:security-crypto:1.1.0-alpha06"

    // Librería para Jetpack DataStore
    implementation "androidx.datastore:datastore-preferences:1.0.0"
}

android {
  compileSdkVersion 35
  buildToolsVersion "35"
  // ndkVersion ""

  defaultConfig {
    minSdkVersion 24
    targetSdkVersion 35

    // Version Information
    versionCode 1
    versionName "1.0.0"

    generatedDensities = []
  }

  aaptOptions {
    additionalParameters "--no-version-vectors"
  }
}
